[SofaDeformable] Bind LinearSpring (#78)
* Fix bindings of STL exporter

* Fix bindings test files copied at configure time with MultiConfig setup

* reorganize projects using folders with IDE like MSVC

* Undo cmake folder properties since it isn't whitelisted for interface targets

* Fix python test files location from the build directory for MSVC

* Fix the Controller on Windows

* Fix some tests on Windows

* Fix remaining tests on windows

* Added initial bindings for ContactListener. Ment for review.

* Fixed the bindings by moving them above the PythonFactory registration.

* Initial test to bind LinearSpring. Fails with boost error: ‘intrusive_ptr_release’ was not declared in this scope

* Commented out a feature that is yet in a PR on SOFA.

* Removed holder type from LinearSpring, as it does not inherit from anything. Added first try at binding SpringForceField. Compiles fine, but results in linking error when called in python.

* Fix undefined symbol for templated SpringForceFields

* Added bindings for several getter and setter functions of SpringForceField. Added documentation for the newly bound functions.

* Add tests for SofaDeformable and some cleanups

Co-authored-by: Jean-Nicolas Brunet <jnbrunet2000@gmail.com>
Co-authored-by: Frederick Roy <fred.roy.me@gmail.com>